### ISSUE TITLE
s3 object download

### ISSUE THREAD

**Issue by chris-brace** [reactiverse/aws-sdk#49] opened 2020-09-04 22:55 UTC
I am trying to download 1000s of S3 objects (2-6mb each) from an s3 bucket simultaneously. I've done basically nothing out of the ordinary. I'm constructing the s3asyncclient like this:

```java
s3AsyncClient = VertxSdkClient.withVertx(S3AsyncClient.builder(), vertx.getOrCreateContext()).build();
```

and calling it like this: 

```java
    final Path p = PATH.resolve(UUID.randomUUID().toString());
    final CompletableFuture<GetObjectResponse> cf = s3AsyncClient.getObject(getLargeImageRequest(index), p);
```

The result, however, is a corrupted image that, from the looks of it is having its data written in the wrong order. This happens even if i only make one request. I did see https://github.com/reactiverse/aws-sdk/issues/35 from last year and was able to get a single file downloading doing like this:

```java

  Future<String> writeFile(Buffer data)
  {
    final Path p = PATH.resolve(UUID.randomUUID().toString() + ".jpg");
    final Promise<Void> promise = Promise.promise();
    vertx.fileSystem().writeFile(p.toString(), data, promise);
    return promise.future().map(p.toString());
  }

  Future<Buffer> getImage(int index, long length)
  {
    final String ebAddress = "s3-forward";
    final MessageProducer<Buffer> producer = vertx.eventBus().sender(ebAddress);
    final VertxAsyncResponseTransformer<GetObjectResponse> transformer = new VertxAsyncResponseTransformer<>(producer);

    final Buffer received = Buffer.buffer();
    final Promise<Buffer> promise = Promise.promise();
    vertx.eventBus().<Buffer>consumer(ebAddress, msg -> {
      received.appendBuffer(msg.body());
      if (received.length() == length)
      {
        promise.complete(received);
      }
    });

    s3AsyncClient.getObject(getLargeImageRequest(index), transformer);

    return promise.future();
  }
```

Is it expected that the default AWS SDK transformer for a `Path` object wont work out of the box? I guess i could use an event bus and my own async response transformer to stream data to file handles as it comes in but this seems like a lot of moving parts.

Can anyone advise how I should proceed here? I can upload the entire project very easily but its really not much more than what I pasted.

**Comment by aesteve** [comment] 2020-09-05 09:15
Can you push your code please. ? Not sure I'll be able to help, but without a proper project that reproduces the issue I'm sure I won't be able to, unfortunately.

From a very naive first look, I don't think you need the event bus at all (and so much boilerplate).
Using a response transformer is a way to tell the SDK what it's gonna do with the response chunks. Any `WriteStream<Buffer>` is acceptable. 

So the question is: what do you want to do with the response chunks? It seems you just need to write them to a file on the FS.
Since a Vert.x `AsyncFile` object is a `WriteStream<Buffer>` which is what `VertxAsyncResponseTransformer` expects you basically just have to write something like:

```java
    final Path p = PATH.resolve(UUID.randomUUID().toString() + ".jpg");
    vertx.fileSystem().open(p.toString(), new OpenOptions().setWrite(true), res -> {
       // check res
      VertxAsyncResponseTransformer<GetObjectResponse> transformer = new VertxAsyncResponseTransformer<>(res.result());
      CompletableFuture<WriteStream<Buffer>> cf = s3AsyncClient.getObject(VertxS3ClientSpec::downloadImgReq, transformer);
      // ...
    });

```

**Comment by chris-brace** [comment] 2020-09-05 19:52
Thanks so much for your timely reply. I don't think i'll be able to get to this today but I see what you're saying and will try it out and update you. If I can't get it to work I will upload my code I originally had the issue with and leave the bucket and two 8k photos open to the public for a while so there's no ambiguity.

**Comment by chris-brace** [comment] 2020-09-08 04:14
It seems like I got it to work!

```java
  /**
   * Open a file at path P
   *
   * @param p The path
   * @return
   */
  Future<AsyncFile> open(Path p)
  {
    final Promise<AsyncFile> prom = Promise.promise();
    vertx.fileSystem().open(p.toString(), new OpenOptions().setWrite(true), prom);
    return prom.future();
  }

  /**
   * Seems like this is all you need to do. 1000s of these execute fine all at once
   *
   * @param file    The async file to write to
   * @param request The S3 SDK request object
   * @return A future that completes when the file is written
   */
  Future<Void> downloadToAsyncFile(AsyncFile file, GetObjectRequest request)
  {
    final VertxAsyncResponseTransformer<GetObjectResponse> transformer = new VertxAsyncResponseTransformer<>(file);
    final CompletableFuture<WriteStream<Buffer>> cf = s3AsyncClient.getObject(request, transformer);
    return Future.fromCompletionStage(cf).onFailure(ignored -> file.close()).mapEmpty();
  }

  /**
   * Open the file, download s3 object to it
   *
   * @param path    The file path to write to
   * @param request The s3 sdk request
   * @return A future containing the abspath of the file created
   */
  Future<String> getImage(Path path, GetObjectRequest request)
  {
    return open(path).compose(file -> downloadToAsyncFile(file, request)).map(path.toString());
  }

```

The only thing im worried about is whether or not I missed any cases where the AsyncFile might not be closed for some reason. I dug through the docs and the code and it's not clear whether or not I should expect this to happen automatically in case of failure.

**Comment by aesteve** [comment] 2020-09-08 05:25
That is more of a generic Vert.x question than a AWS SDK one.

You can try asking it on Gitter or Stackoverflow or the Google Groups.

Thank you

Le mar. 8 sept. 2020 à 06:14, chris galardi <notifications@github.com> a
écrit :

**Comment by aesteve** [comment] 2020-09-11 07:27
May I close this? Is it good for you?

**Closed** 2020-11-07 10:29 UTC
